spring:
#  data:
#    mongodb:
#      url: jdbc:mongodb://atlas-sql-670f86da66050b5489071084-mmpf3.a.query.mongodb.net/sample_mflix?ssl=true&authSource=admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1006
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update